# Datentransformation Beispiel

In [7]:
import numpy as np

from sklearn.model_selection import train_test_split # for splitting the data
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler

In [2]:
x, y = np.arange(-8,8).reshape((8,2)), range(8)

In [14]:
x

array([[-8, -7],
       [-6, -5],
       [-4, -3],
       [-2, -1],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [32]:
# Splitting Train and test-data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


In [33]:
X_train

array([[ 0,  1],
       [-2, -1],
       [-4, -3],
       [ 6,  7],
       [ 4,  5],
       [-8, -7]])

### Min Max Scaler

In [35]:
# Lösung vom Adro ist bullshit, weil Werte größer 1 und kleiner 0 beim min-max rauskommen können
minmax_scale = MinMaxScaler()
minmax_scale.fit(X_train)
X_train_scaled = minmax_scale.transform(X_train)
print(X_train_scaled)
X_test_scaled = minmax_scale.transform(X_test)
print(X_test_scaled)

[[0.57142857 0.57142857]
 [0.42857143 0.42857143]
 [0.28571429 0.28571429]
 [1.         1.        ]
 [0.85714286 0.85714286]
 [0.         0.        ]]
[[0.14285714 0.14285714]
 [0.71428571 0.71428571]]
